In [1]:
import numpy as np

In [5]:
a=np.arange(2,101,2)

In [6]:
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
l=[]
for i in range(2,101,2):
  l.append(i)
l

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [9]:
a=np.array(l)

In [10]:
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
a=np.arange(5,51,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


In [14]:
a=np.linspace(1,3,4)
a

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [16]:
a=np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
a=np.random.rand(5)
print(a)

[0.51898563 0.66393368 0.91705908 0.46182561 0.95795131]


In [22]:
a=np.random.rand(5,2)
print(a)

[[0.70442382 0.87736801]
 [0.22657381 0.25822204]
 [0.43764391 0.59858732]
 [0.18937683 0.46977187]
 [0.90843172 0.50315213]]


In [23]:
a=np.random.rand(5,2,3)
print(a)

[[[0.34388313 0.62048675 0.70740622]
  [0.30798902 0.79627975 0.3382734 ]]

 [[0.20597563 0.77758884 0.90501423]
  [0.13842766 0.85695338 0.36175129]]

 [[0.04591725 0.2099526  0.13937096]
  [0.30028588 0.94258116 0.95858155]]

 [[0.53281849 0.26473537 0.99675311]
  [0.7074918  0.79412371 0.13218174]]

 [[0.59487072 0.64867972 0.72320714]
  [0.7274576  0.63011659 0.03491014]]]


In [35]:
a=np.random.randint(1,6)
print(a)

1


In [36]:
a=np.random.randint(1,6,(4))
print(a)

[5 4 5 4]


In [37]:
a=np.random.randint(1,6,(4,2))
print(a)

[[2 4]
 [2 2]
 [2 2]
 [4 5]]


In [40]:
a=np.random.randint(1,6,(4,8,5))
print(a)

[[[5 4 5 3 5]
  [5 5 5 3 4]
  [2 1 1 3 5]
  [5 4 3 4 5]
  [5 1 1 2 1]
  [1 3 4 4 1]
  [5 4 3 1 5]
  [2 2 1 3 1]]

 [[5 4 3 4 4]
  [3 4 2 5 2]
  [3 5 5 5 4]
  [1 3 3 4 4]
  [1 5 3 3 4]
  [2 4 5 4 5]
  [4 1 1 5 1]
  [1 3 3 5 5]]

 [[3 3 1 1 4]
  [1 4 4 4 1]
  [1 5 1 4 2]
  [1 5 4 2 1]
  [2 4 3 1 4]
  [3 1 4 5 4]
  [1 3 5 3 2]
  [1 4 1 5 1]]

 [[1 1 5 4 1]
  [2 1 3 5 1]
  [4 5 2 4 5]
  [3 2 5 4 2]
  [2 1 4 1 5]
  [2 2 2 2 2]
  [1 3 2 2 4]
  [4 2 3 3 4]]]


In [41]:
a=np.random.randn()
print(a)

-0.6649799939550017


In [43]:
a=np.random.randn(5)
print(a)

[-0.36544186 -1.31629107 -0.65478344 -2.42995611 -0.43240451]


In [44]:
a=np.random.randn(5,2)
print(a)

[[ 0.21156215 -0.7804936 ]
 [-0.393279   -0.70971156]
 [ 0.85480111 -1.25923841]
 [-0.8601616  -0.01870978]
 [-0.59906881 -0.81301353]]


In [46]:
a=np.random.randn(3,2,4)
print(a)

[[[ 0.42491797  1.37497847 -0.35871964  1.13158009]
  [-0.08208817 -1.20366061  0.42613511 -1.04730038]]

 [[-1.25984167 -2.07927062 -1.43197821 -1.00954709]
  [ 0.03862847  0.61470849  0.67074566 -1.85200631]]

 [[ 0.57073266 -0.58483882  2.25328795  1.25750131]
  [-0.43571233 -0.41800304  1.57048391  0.27352177]]]


In [61]:
a=np.random.choice([1,2,3,4,7,8],4)
print(a)

[8 8 8 3]


In [62]:
a=np.random.choice([1,2,3,4,7,8],(4,1))
print(a)

[[7]
 [7]
 [4]
 [2]]


In [63]:
a=np.random.choice([1,2,3,4,7,8],(4,3,5))
print(a)

[[[2 1 1 2 1]
  [3 2 2 2 4]
  [7 1 7 1 3]]

 [[1 3 8 1 8]
  [1 2 1 7 7]
  [1 2 7 2 3]]

 [[1 7 8 8 7]
  [4 1 8 8 8]
  [3 8 1 1 3]]

 [[1 4 2 8 8]
  [2 3 7 8 1]
  [3 4 8 4 8]]]


In [73]:
a=np.arange(0,10)
print(a)
b=a.reshape(5,2)
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2


In [76]:
a=np.arange(0,10)
print(a)
b=a.reshape(5,1,2)
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
3


In [77]:
a=np.arange(1,13)
print(a)
b=a.reshape(2,3,2)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [79]:
a=np.arange(1,49)
print(a)
b=a.reshape(4,3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


In [85]:
a=np.arange(1,49)
print(a)
b=a.reshape(4,3,4).astype(float)

print(b)
print(b.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]

 [[25. 26. 27. 28.]
  [29. 30. 31. 32.]
  [33. 34. 35. 36.]]

 [[37. 38. 39. 40.]
  [41. 42. 43. 44.]
  [45. 46. 47. 48.]]]
float64


In [89]:
a=np.tile([1,2,3],10)
print(a)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [92]:
a=np.tile([[1,2,3],[4,5,6]],(2,4,5))
print(a)


[[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]

 [[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]
  [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
  [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]]
