In [ ]:
import numpy as np

In [ ]:
l=[[32,48,99,42],[45,67,22,11]]
a=np.array(l)

In [ ]:
print(a)

[[32 48 99 42]
 [45 67 22 11]]


In [ ]:
print(np.max(a))

99


In [ ]:
print(np.min(a))

11


In [ ]:
print(np.argmax(a))

2


In [ ]:
print(np.argmin(a))

7


In [ ]:
a=np.array([0.9,8.9,8.4,8.3,8.5,0.5,0.6])

In [ ]:
print(a)

[0.9 8.9 8.4 8.3 8.5 0.5 0.6]


In [ ]:
print(np.round(a))

[1. 9. 8. 8. 8. 0. 1.]


In [ ]:
print(np.ceil(a))

[1. 9. 9. 9. 9. 1. 1.]


In [ ]:
print(np.floor(a))

[0. 8. 8. 8. 8. 0. 0.]


In [ ]:
a=np.array([10,15,20])
b=np.array([2,1,3])

In [ ]:
print(a)

[10 15 20]


In [ ]:
print(b)

[2 1 3]


In [ ]:
print(a+b)

[12 16 23]


In [ ]:
print(a*b)

[20 15 60]


In [ ]:
print(a-b)

[ 8 14 17]


In [ ]:
print(b-a)

[ -8 -14 -17]


In [ ]:
print(a**b)

[ 100   15 8000]


In [ ]:
print(a/b)

[ 5.         15.          6.66666667]


In [ ]:
print(a%b)

[0 0 2]


In [ ]:
print(np.add(a,b))

[12 16 23]


In [ ]:
print(np.multiply(a,b))

[20 15 60]


In [ ]:
print(np.subtract(a,b))

[ 8 14 17]


In [ ]:
print(np.pow(a,b))

[ 100   15 8000]


In [ ]:
print(np.divide(a,b))

[ 5.         15.          6.66666667]


In [ ]:
a=np.arange(100,112).reshape(3,4)
print(a)

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]


In [ ]:
print(np.max(a,axis=0))

[108 109 110 111]


In [ ]:
print(np.max(a,axis=1))

111


In [ ]:
a=np.array([[45,67,22],[67,8,98],[34,11,0]])

In [ ]:
print(a)

[[45 67 22]
 [67  8 98]
 [34 11  0]]


In [ ]:
print(np.max(a,axis=1))

[67 98 34]


In [ ]:
print(np.min(a,axis=0))

[34  8  0]


In [ ]:
print(np.argmax(a,axis=0))

[1 0 1]


In [ ]:
print(np.argmin(a,axis=0))

[2 1 2]


In [ ]:
print(np.argmin(a,axis=1))

[2 1 2]


In [ ]:
a=np.array([5,3,4,6,7,8,2,3,5])
print(a)

[5 3 4 6 7 8 2 3 5]


In [ ]:
print(np.median(a))

5.0


In [ ]:
l=[5,6,7,8,9]
print(l)

[5, 6, 7, 8, 9]


In [ ]:
a=np.array(l)
print(a)

[5 6 7 8 9]


In [ ]:
t=(4,5,3,2,1)
print(t)

(4, 5, 3, 2, 1)


In [ ]:
a=np.array(t)
print(a)

[4 5 3 2 1]


In [ ]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.eye(4,6,3)
print(a)

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
a=np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.arange(5,10,1)
print(a)

[5 6 7 8 9]


In [ ]:
a=np.linspace(5,10,5)
print(a)

[ 5.    6.25  7.5   8.75 10.  ]


In [ ]:
a=np.random.rand(4,5)
print(a)

[[0.10871543 0.20911061 0.19094143 0.87163768 0.30731508]
 [0.21880673 0.8014211  0.34565093 0.61999258 0.45877277]
 [0.65700452 0.27888238 0.03510534 0.35495067 0.20610861]
 [0.34042785 0.27639894 0.06045203 0.84841652 0.82160602]]


In [ ]:
a=np.random.randint(2,6,(5,6))
print(a)

[[2 5 2 5 4 3]
 [5 5 5 4 2 2]
 [2 3 4 5 2 3]
 [4 3 3 4 4 4]
 [4 2 5 5 4 4]]


In [ ]:
a=np.random.randn(3,4)
print(a)

[[-1.06658986 -1.38738245 -1.1356409  -1.5152466 ]
 [-0.74003101 -0.61215435  0.76728347 -0.6406666 ]
 [ 0.87740059  0.40718427  1.16178116  0.48032178]]


In [ ]:
a=np.random.choice([10,40,90],(5))
print(a)

[10 90 40 90 40]


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]


In [ ]:
b=a.flatten()

In [ ]:
print(b)

[1 2 3 4 5 6 7 8 9 9 8 7]
