In [38]:
import numpy as np

In [39]:
a=np.arange(101,121)

In [40]:
print(a)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]


In [41]:
b=a.reshape(4,5)

In [42]:
print(b)

[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]]


In [43]:
print(b[1,2])

108


In [44]:
print(b[1:3:1,1:4:1])

[[107 108 109]
 [112 113 114]]


In [45]:
print(b[::3,::4])

[[101 105]
 [116 120]]


In [46]:
print(b[::,::2])

[[101 103 105]
 [106 108 110]
 [111 113 115]
 [116 118 120]]


In [47]:
print(b[::2,::2])

[[101 103 105]
 [111 113 115]]


In [48]:
print(b[1::2,3::2])

[[109]
 [119]]


3-d slicing

In [49]:
a=np.arange(101,137)
print(a)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]


In [50]:
b=a.reshape(3,4,3)

In [51]:
print(b)

[[[101 102 103]
  [104 105 106]
  [107 108 109]
  [110 111 112]]

 [[113 114 115]
  [116 117 118]
  [119 120 121]
  [122 123 124]]

 [[125 126 127]
  [128 129 130]
  [131 132 133]
  [134 135 136]]]


In [52]:
print(b[1,2,1])

120


In [53]:
print(b[::,1:3:1,1:2:1])

[[[105]
  [108]]

 [[117]
  [120]]

 [[129]
  [132]]]


In [54]:
print(b[2::,1:3:1,0:1:1])

[[[128]
  [131]]]


In [55]:
print(b[0:3:1,0:4:3,0:3:2])

[[[101 103]
  [110 112]]

 [[113 115]
  [122 124]]

 [[125 127]
  [134 136]]]


In [56]:
print(b[0:3:2,1:4:2,0:3:2])

[[[104 106]
  [110 112]]

 [[128 130]
  [134 136]]]


mathamatical functions

In [57]:
a=np.array([1,2,1,3,4,5,5])
print(a)

[1 2 1 3 4 5 5]


In [58]:
print(np.sum(a))

21


In [59]:
print(np.max(a))

5


In [60]:
print(np.min(a))

1


In [61]:
print(np.cumsum(a).sum())

63


In [62]:
print(np.prod(a))

600


In [63]:
print(np.cumprod(a))

[  1   2   2   6  24 120 600]


In [65]:
print(np.cumprod(a).prod())

41472000


In [66]:
print(np.cumprod(a).sum())

755


In [67]:
print(np.std(a))

1.6035674514745464


In [68]:
print(np.var(a))

2.5714285714285716


In [69]:
print(np.mean(a))

3.0
