In [1]:
import numpy as np

In [55]:
l=[1,2,3,4]
l
print(type(l))

<class 'list'>


In [56]:
a=np.array(l)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)   # size*itemsize

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64
8
32


2-d array

In [57]:
l=[[1,2,3],[4,5,6.0]]
l

[[1, 2, 3], [4, 5, 6.0]]

In [58]:
a=np.array(l)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
6
float64
8
48


3-d array'

In [59]:
l=[[[1,2,3],[4,5,6],[7,8,9]],[[8,9,0],[3,4,5],[6,7,'8']]]
l

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[8, 9, 0], [3, 4, 5], [6, 7, '8']]]

In [60]:
a=np.array(l)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

[[['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]

 [['8' '9' '0']
  ['3' '4' '5']
  ['6' '7' '8']]]
3
(2, 3, 3)
18
<U21
84
1512
