In [1]:
import numpy as np

In [2]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [3]:
print(a[2])

4


In [4]:
print(a[4])

8


In [5]:
print(a[-1])

8


In [6]:
print(a[-4])

2


indexing in 2-d

In [7]:
a=np.arange(50,71)
print(a)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [8]:
b=a.reshape(3,7)

In [9]:
print(b)

[[50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70]]


In [10]:
print(b[1,3])

60


In [11]:
print(b[1][3])

60


In [12]:
print(b[2,6])

70


In [14]:
print(b[-1,-6])

65


In [15]:
print(b[-2,-2])

62


In [16]:
print(b[-2,1])

58


In [17]:
print(b[-3,6])

56


In [18]:
print(b[2,-4])

67


In [19]:
a=np.arange(100,180)
print(a)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179]


In [20]:
b=a.reshape(4,4,5)
print(b)

[[[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[120 121 122 123 124]
  [125 126 127 128 129]
  [130 131 132 133 134]
  [135 136 137 138 139]]

 [[140 141 142 143 144]
  [145 146 147 148 149]
  [150 151 152 153 154]
  [155 156 157 158 159]]

 [[160 161 162 163 164]
  [165 166 167 168 169]
  [170 171 172 173 174]
  [175 176 177 178 179]]]


In [21]:
print(b[-3,2,-2])

133


In [23]:
print(b[-4,3,3])

118


In [25]:
print(b[-1,-3,-2])

168


slicing

In [27]:
a=np.arange(50,100,5)
print(a)

[50 55 60 65 70 75 80 85 90 95]


In [28]:
print(a[2:7:1])

[60 65 70 75 80]


In [29]:
print(a[2:7])

[60 65 70 75 80]


In [30]:
print(a[:5:2])

[50 60 70]


In [32]:
print(a[1:8:2])

[55 65 75 85]


In [33]:
print(a[1:-2:3])

[55 70 85]


In [35]:
print(a[-2:1:-3])

[90 75 60]


In [39]:
print(a[8::-2])

[90 80 70 60 50]


In [40]:
print(a[-3:-10:-2])

[85 75 65 55]
