In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,54,6]

In [ ]:
a=np.array(l)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 1  2  3  4 54  6]


In [ ]:
l1=[[1,2,3,4],[5,6,7,8]]

In [ ]:
b=np.array(l1)

In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
l2=[[[1,2,3],[4,5,6]],[[7,8,9],[8,9,0]]]

In [ ]:
c=np.array(l2)
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 0]]]


properties of array

ndim  

shape

size

itemsize

nbytes

dtype

In [ ]:
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.itemsize)
print(c.dtype)
print(c.nbytes)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 0]]]
3
(2, 2, 3)
12
8
int64
96


In [ ]:
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 0]]]


In [ ]:
d=c.flatten()

In [ ]:
print(d)

[1 2 3 4 5 6 7 8 9 8 9 0]


In [ ]:
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 0]]]


In [ ]:
d=c.reshape(4,3)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 9 0]]


In [ ]:
print(np.sum(c))

62


In [ ]:
print(np.cumsum(c))

[ 1  3  6 10 15 21 28 36 45 53 62 62]


In [ ]:
print(np.prod(c))

0


In [ ]:
print(np.cumprod(c))

[       1        2        6       24      120      720     5040    40320
   362880  2903040 26127360        0]


In [ ]:
print(np.var(c))

9.138888888888888


In [ ]:
print(np.std(c))

3.0230595245361753


In [ ]:
print(np.mean(c))

5.166666666666667


In [ ]:
print(np.min(c))

0


In [ ]:
print(np.max(c))

9


In [ ]:
print(np.median(c))

5.5


In [ ]:
print(np.argmax(c))

8


In [ ]:
print(np.argmin(c))

11


In [ ]:
a=np.array([4,5,6])
b=np.array([7,8,9])

In [ ]:
print(a+b)

[11 13 15]


In [ ]:
print(np.add(a,b))

[11 13 15]


In [ ]:
print(a*b)

[28 40 54]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(b-a)

[3 3 3]


In [ ]:
print(a/b)

[0.57142857 0.625      0.66666667]


In [ ]:
print(a%b)

[4 5 6]


In [ ]:
a=np.arange(50,74).reshape(4,6)
print(a)

[[50 51 52 53 54 55]
 [56 57 58 59 60 61]
 [62 63 64 65 66 67]
 [68 69 70 71 72 73]]


In [ ]:
print(np.max(a))
print(np.min(a))

73
50


In [ ]:
print(np.min(a,axis=1))

[50 56 62 68]


In [ ]:
print(np.min(a,axis=0))

[50 51 52 53 54 55]


In [ ]:
print(np.max(a,axis=0))

[68 69 70 71 72 73]


In [ ]:
print(np.max(a,axis=1))

[55 61 67 73]
